version: '3.5'
services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
  myapp:
    tty: true
    image: laravel-simple-counter
    build: .
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
